<?php
session_start();
// Generate CSRF token
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

// ==================== DATABASE CONFIGURATION ====================
define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'icourt');


// Create database connection
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// ==================== TABLE SETUP ====================

// Create thanas_master table
$create_thanas_master = "CREATE TABLE IF NOT EXISTS thanas_master (
    id INT AUTO_INCREMENT PRIMARY KEY,
    division VARCHAR(50) NOT NULL,
    district VARCHAR(50) NOT NULL,
    thana_name VARCHAR(50) NOT NULL
)";
$conn->query($create_thanas_master);

// Check if table is empty before inserting
$check_thanas = "SELECT COUNT(*) as count FROM thanas_master";
$result = $conn->query($check_thanas);
$row = $result->fetch_assoc();

if ($row['count'] == 0) {
    // Full thana data for all divisions
        $thana_data = [
        // Barishal Division
        ['Barishal', 'Barishal', 'Barishal Sadar'],
        ['Barishal', 'Barishal', 'Bakerganj'],
        ['Barishal', 'Barishal', 'Babuganj'],
        ['Barishal', 'Barishal', 'Wazirpur'],
        ['Barishal', 'Barishal', 'Banaripara'],
        ['Barishal', 'Barishal', 'Gournadi'],
        ['Barishal', 'Barishal', 'Agailjhara'],
        ['Barishal', 'Barishal', 'Mehendiganj'],
        ['Barishal', 'Barishal', 'Muladi'],
        ['Barishal', 'Barishal', 'Hizla'],
        ['Barishal', 'Bhola', 'Bhola Sadar'],
        ['Barishal', 'Bhola', 'Daulatkhan'],
        ['Barishal', 'Bhola', 'Burhanuddin'],
        ['Barishal', 'Bhola', 'Tazumuddin'],
        ['Barishal', 'Bhola', 'Lalmohan'],
        ['Barishal', 'Bhola', 'Char Fasson'],
        ['Barishal', 'Bhola', 'Manpura'],
        ['Barishal', 'Jhalokati', 'Jhalokati Sadar'],
        ['Barishal', 'Jhalokati', 'Kathalia'],
        ['Barishal', 'Jhalokati', 'Nalchity'],
        ['Barishal', 'Jhalokati', 'Rajapur'],
        ['Barishal', 'Patuakhali', 'Patuakhali Sadar'],
        ['Barishal', 'Patuakhali', 'Mirzaganj'],
        ['Barishal', 'Patuakhali', 'Galachipa'],
        ['Barishal', 'Patuakhali', 'Dashmina'],
        ['Barishal', 'Patuakhali', 'Kalapara'],
        ['Barishal', 'Patuakhali', 'Bauphal'],
        ['Barishal', 'Patuakhali', 'Dumki'],
        ['Barishal', 'Pirojpur', 'Pirojpur Sadar'],
        ['Barishal', 'Pirojpur', 'Nazirpur'],
        ['Barishal', 'Pirojpur', 'Kawkhali'],
        ['Barishal', 'Pirojpur', 'Zianagar'],
        ['Barishal', 'Pirojpur', 'Bhandaria'],
        ['Barishal', 'Pirojpur', 'Mathbaria'],
        ['Barishal', 'Pirojpur', 'Nesarabad'],
        
        // Chattogram Division
        ['Chattogram', 'Bandarban', 'Bandarban Sadar'],
        ['Chattogram', 'Bandarban', 'Thanchi'],
        ['Chattogram', 'Bandarban', 'Lama'],
        ['Chattogram', 'Bandarban', 'Naikhongchhari'],
        ['Chattogram', 'Bandarban', 'Ali kadam'],
        ['Chattogram', 'Bandarban', 'Rowangchhari'],
        ['Chattogram', 'Bandarban', 'Ruma'],
        ['Chattogram', 'Brahmanbaria', 'Brahmanbaria Sadar'],
        ['Chattogram', 'Brahmanbaria', 'Kasba'],
        ['Chattogram', 'Brahmanbaria', 'Nasirnagar'],
        ['Chattogram', 'Brahmanbaria', 'Sarail'],
        ['Chattogram', 'Brahmanbaria', 'Ashuganj'],
        ['Chattogram', 'Brahmanbaria', 'Akhaura'],
        ['Chattogram', 'Brahmanbaria', 'Nabinagar'],
        ['Chattogram', 'Brahmanbaria', 'Bancharampur'],
        ['Chattogram', 'Brahmanbaria', 'Bijoynagar'],
        ['Chattogram', 'Chandpur', 'Chandpur Sadar'],
        ['Chattogram', 'Chandpur', 'Faridganj'],
        ['Chattogram', 'Chandpur', 'Haimchar'],
        ['Chattogram', 'Chandpur', 'Haziganj'],
        ['Chattogram', 'Chandpur', 'Kachua'],
        ['Chattogram', 'Chandpur', 'Matlab Uttar'],
        ['Chattogram', 'Chandpur', 'Matlab Dakshin'],
        ['Chattogram', 'Chandpur', 'Shahrasti'],
        ['Chattogram', 'Chattogram', 'Chattogram Kotwali'],
        ['Chattogram', 'Chattogram', 'Panchlaish'],
        ['Chattogram', 'Chattogram', 'Pahartali'],
        ['Chattogram', 'Chattogram', 'Double Mooring'],
        ['Chattogram', 'Chattogram', 'Kotwali'],
        ['Chattogram', 'Chattogram', 'Bandar'],
        ['Chattogram', 'Chattogram', 'Chandgaon'],
        ['Chattogram', 'Chattogram', 'Bakalia'],
        ['Chattogram', 'Chattogram', 'Patenga'],
        ['Chattogram', 'Chattogram', 'Karnafuli'],
        ['Chattogram', 'Chattogram', 'Anwara'],
        ['Chattogram', 'Chattogram', 'Banshkhali'],
        ['Chattogram', 'Chattogram', 'Boalkhali'],
        ['Chattogram', 'Chattogram', 'Chandanaish'],
        ['Chattogram', 'Chattogram', 'Fatikchhari'],
        ['Chattogram', 'Chattogram', 'Hathazari'],
        ['Chattogram', 'Chattogram', 'Lohagara'],
        ['Chattogram', 'Chattogram', 'Mirsharai'],
        ['Chattogram', 'Chattogram', 'Patiya'],
        ['Chattogram', 'Chattogram', 'Rangunia'],
        ['Chattogram', 'Chattogram', 'Raozan'],
        ['Chattogram', 'Chattogram', 'Sandwip'],
        ['Chattogram', 'Chattogram', 'Satkania'],
        ['Chattogram', 'Chattogram', 'Sitakunda'],
        ['Chattogram', 'Cumilla', 'Cumilla Sadar'],
        ['Chattogram', 'Cumilla', 'Barura'],
        ['Chattogram', 'Cumilla', 'Brahmanpara'],
        ['Chattogram', 'Cumilla', 'Burichang'],
        ['Chattogram', 'Cumilla', 'Chandina'],
        ['Chattogram', 'Cumilla', 'Chauddagram'],
        ['Chattogram', 'Cumilla', 'Daudkandi'],
        ['Chattogram', 'Cumilla', 'Debidwar'],
        ['Chattogram', 'Cumilla', 'Homna'],
        ['Chattogram', 'Cumilla', 'Laksam'],
        ['Chattogram', 'Cumilla', 'Muradnagar'],
        ['Chattogram', 'Cumilla', 'Nangalkot'],
        ['Chattogram', 'Cumilla', 'Cumilla Adarsha Sadar'],
        ['Chattogram', 'Cumilla', 'Meghna'],
        ['Chattogram', 'Cumilla', 'Titas'],
        ['Chattogram', 'Cumilla', 'Monohargonj'],
        ['Chattogram', 'Cumilla', 'Sadar South'],
        ['Chattogram', 'Cox\'s Bazar', 'Cox\'s Bazar Sadar'],
        ['Chattogram', 'Cox\'s Bazar', 'Chakaria'],
        ['Chattogram', 'Cox\'s Bazar', 'Kutubdia'],
        ['Chattogram', 'Cox\'s Bazar', 'Ukhiya'],
        ['Chattogram', 'Cox\'s Bazar', 'Moheshkhali'],
        ['Chattogram', 'Cox\'s Bazar', 'Pekua'],
        ['Chattogram', 'Cox\'s Bazar', 'Ramu'],
        ['Chattogram', 'Cox\'s Bazar', 'Teknaf'],
        ['Chattogram', 'Feni', 'Feni Sadar'],
        ['Chattogram', 'Feni', 'Chhagalnaiya'],
        ['Chattogram', 'Feni', 'Daganbhuiyan'],
        ['Chattogram', 'Feni', 'Parshuram'],
        ['Chattogram', 'Feni', 'Fulgazi'],
        ['Chattogram', 'Feni', 'Sonagazi'],
        ['Chattogram', 'Khagrachhari', 'Khagrachhari Sadar'],
        ['Chattogram', 'Khagrachhari', 'Dighinala'],
        ['Chattogram', 'Khagrachhari', 'Panchhari'],
        ['Chattogram', 'Khagrachhari', 'Laxmichhari'],
        ['Chattogram', 'Khagrachhari', 'Mohalchhari'],
        ['Chattogram', 'Khagrachhari', 'Ramgarh'],
        ['Chattogram', 'Khagrachhari', 'Manikchhari'],
        ['Chattogram', 'Khagrachhari', 'Matiranga'],
        ['Chattogram', 'Lakshmipur', 'Lakshmipur Sadar'],
        ['Chattogram', 'Lakshmipur', 'Raipur'],
        ['Chattogram', 'Lakshmipur', 'Ramganj'],
        ['Chattogram', 'Lakshmipur', 'Ramgati'],
        ['Chattogram', 'Lakshmipur', 'Komol Nagar'],
        ['Chattogram', 'Noakhali', 'Noakhali Sadar'],
        ['Chattogram', 'Noakhali', 'Begumganj'],
        ['Chattogram', 'Noakhali', 'Chatkhil'],
        ['Chattogram', 'Noakhali', 'Companiganj'],
        ['Chattogram', 'Noakhali', 'Hatiya'],
        ['Chattogram', 'Noakhali', 'Senbagh'],
        ['Chattogram', 'Noakhali', 'Sonaimuri'],
        ['Chattogram', 'Noakhali', 'Subarnachar'],
        ['Chattogram', 'Noakhali', 'Kabirhat'],
        ['Chattogram', 'Rangamati', 'Rangamati Sadar'],
        ['Chattogram', 'Rangamati', 'Belaichhari'],
        ['Chattogram', 'Rangamati', 'Bagaichhari'],
        ['Chattogram', 'Rangamati', 'Barkal'],
        ['Chattogram', 'Rangamati', 'Juraichhari'],
        ['Chattogram', 'Rangamati', 'Rajasthali'],
        ['Chattogram', 'Rangamati', 'Kaptai'],
        ['Chattogram', 'Rangamati', 'Langadu'],
        ['Chattogram', 'Rangamati', 'Nannerchar'],
        ['Chattogram', 'Rangamati', 'Kaukhali'],
        
        // Dhaka Division
        ['Dhaka', 'Dhaka', 'Dhanmondi'],
        ['Dhaka', 'Dhaka', 'Mohammadpur'],
        ['Dhaka', 'Dhaka', 'Tejgaon'],
        ['Dhaka', 'Dhaka', 'Ramna'],
        ['Dhaka', 'Dhaka', 'Motijheel'],
        ['Dhaka', 'Dhaka', 'Paltan'],
        ['Dhaka', 'Dhaka', 'Gulshan'],
        ['Dhaka', 'Dhaka', 'Mirpur'],
        ['Dhaka', 'Dhaka', 'Sher-e-Bangla Nagar'],
        ['Dhaka', 'Dhaka', 'Uttara'],
        ['Dhaka', 'Dhaka', 'Khilgaon'],
        ['Dhaka', 'Dhaka', 'Sabujbagh'],
        ['Dhaka', 'Dhaka', 'Cantonment'],
        ['Dhaka', 'Dhaka', 'Demra'],
        ['Dhaka', 'Dhaka', 'Shyampur'],
        ['Dhaka', 'Dhaka', 'Badda'],
        ['Dhaka', 'Dhaka', 'Kafrul'],
        ['Dhaka', 'Dhaka', 'Kamrangirchar'],
        ['Dhaka', 'Dhaka', 'Kotwali'],
        ['Dhaka', 'Dhaka', 'Lalbagh'],
        ['Dhaka', 'Dhaka', 'Hazaribagh'],
        ['Dhaka', 'Faridpur', 'Faridpur Sadar'],
        ['Dhaka', 'Faridpur', 'Alfadanga'],
        ['Dhaka', 'Faridpur', 'Boalmari'],
        ['Dhaka', 'Faridpur', 'Sadarpur'],
        ['Dhaka', 'Faridpur', 'Nagarkanda'],
        ['Dhaka', 'Faridpur', 'Bhanga'],
        ['Dhaka', 'Faridpur', 'Charbhadrasan'],
        ['Dhaka', 'Faridpur', 'Madhukhali'],
        ['Dhaka', 'Faridpur', 'Saltha'],
        ['Dhaka', 'Gazipur', 'Gazipur Sadar'],
        ['Dhaka', 'Gazipur', 'Kaliakair'],
        ['Dhaka', 'Gazipur', 'Kaliganj'],
        ['Dhaka', 'Gazipur', 'Kapasia'],
        ['Dhaka', 'Gazipur', 'Sreepur'],
        ['Dhaka', 'Gopalganj', 'Gopalganj Sadar'],
        ['Dhaka', 'Gopalganj', 'Kashiani'],
        ['Dhaka', 'Gopalganj', 'Kotalipara'],
        ['Dhaka', 'Gopalganj', 'Muksudpur'],
        ['Dhaka', 'Gopalganj', 'Tungipara'],
        ['Dhaka', 'Kishoreganj', 'Kishoreganj Sadar'],
        ['Dhaka', 'Kishoreganj', 'Austagram'],
        ['Dhaka', 'Kishoreganj', 'Bajitpur'],
        ['Dhaka', 'Kishoreganj', 'Bhairab'],
        ['Dhaka', 'Kishoreganj', 'Hossainpur'],
        ['Dhaka', 'Kishoreganj', 'Itna'],
        ['Dhaka', 'Kishoreganj', 'Karimganj'],
        ['Dhaka', 'Kishoreganj', 'Katiadi'],
        ['Dhaka', 'Kishoreganj', 'Kuliarchar'],
        ['Dhaka', 'Kishoreganj', 'Mithamain'],
        ['Dhaka', 'Kishoreganj', 'Nikli'],
        ['Dhaka', 'Kishoreganj', 'Pakundia'],
        ['Dhaka', 'Kishoreganj', 'Tarail'],
        ['Dhaka', 'Madaripur', 'Madaripur Sadar'],
        ['Dhaka', 'Madaripur', 'Kalkini'],
        ['Dhaka', 'Madaripur', 'Rajoir'],
        ['Dhaka', 'Madaripur', 'Shibchar'],
        ['Dhaka', 'Manikganj', 'Manikganj Sadar'],
        ['Dhaka', 'Manikganj', 'Singair'],
        ['Dhaka', 'Manikganj', 'Shibalaya'],
        ['Dhaka', 'Manikganj', 'Saturia'],
        ['Dhaka', 'Manikganj', 'Harirampur'],
        ['Dhaka', 'Manikganj', 'Ghior'],
        ['Dhaka', 'Manikganj', 'Daulatpur'],
        ['Dhaka', 'Munshiganj', 'Munshiganj Sadar'],
        ['Dhaka', 'Munshiganj', 'Lohajang'],
        ['Dhaka', 'Munshiganj', 'Sreenagar'],
        ['Dhaka', 'Munshiganj', 'Sirajdikhan'],
        ['Dhaka', 'Munshiganj', 'Tongibari'],
        ['Dhaka', 'Munshiganj', 'Gazaria'],
        ['Dhaka', 'Narayanganj', 'Narayanganj Sadar'],
        ['Dhaka', 'Narayanganj', 'Araihazar'],
        ['Dhaka', 'Narayanganj', 'Bandar'],
        ['Dhaka', 'Narayanganj', 'Rupganj'],
        ['Dhaka', 'Narayanganj', 'Sonargaon'],
        ['Dhaka', 'Narayanganj', 'Fatullah'],
        ['Dhaka', 'Narayanganj', 'Siddirganj'],
        ['Dhaka', 'Narsingdi', 'Narsingdi Sadar'],
        ['Dhaka', 'Narsingdi', 'Belabo'],
        ['Dhaka', 'Narsingdi', 'Monohardi'],
        ['Dhaka', 'Narsingdi', 'Palash'],
        ['Dhaka', 'Narsingdi', 'Raipura'],
        ['Dhaka', 'Narsingdi', 'Shibpur'],
        ['Dhaka', 'Rajbari', 'Rajbari Sadar'],
        ['Dhaka', 'Rajbari', 'Baliakandi'],
        ['Dhaka', 'Rajbari', 'Goalandaghat'],
        ['Dhaka', 'Rajbari', 'Pangsha'],
        ['Dhaka', 'Rajbari', 'Kalukhali'],
        ['Dhaka', 'Shariatpur', 'Shariatpur Sadar'],
        ['Dhaka', 'Shariatpur', 'Bhedarganj'],
        ['Dhaka', 'Shariatpur', 'Damudya'],
        ['Dhaka', 'Shariatpur', 'Gosairhat'],
        ['Dhaka', 'Shariatpur', 'Naria'],
        ['Dhaka', 'Shariatpur', 'Zajira'],
        ['Dhaka', 'Shariatpur', 'Shakhipur'],
        ['Dhaka', 'Tangail', 'Tangail Sadar'],
        ['Dhaka', 'Tangail', 'Sakhipur'],
        ['Dhaka', 'Tangail', 'Basail'],
        ['Dhaka', 'Tangail', 'Madhupur'],
        ['Dhaka', 'Tangail', 'Ghatail'],
        ['Dhaka', 'Tangail', 'Kalihati'],
        ['Dhaka', 'Tangail', 'Nagarpur'],
        ['Dhaka', 'Tangail', 'Mirzapur'],
        ['Dhaka', 'Tangail', 'Gopalpur'],
        ['Dhaka', 'Tangail', 'Delduar'],
        ['Dhaka', 'Tangail', 'Bhuapur'],
        ['Dhaka', 'Tangail', 'Dhanbari'],
        
        // Khulna Division
        ['Khulna', 'Bagerhat', 'Bagerhat Sadar'],
        ['Khulna', 'Bagerhat', 'Chitalmari'],
        ['Khulna', 'Bagerhat', 'Fakirhat'],
        ['Khulna', 'Bagerhat', 'Kachua'],
        ['Khulna', 'Bagerhat', 'Mollahat'],
        ['Khulna', 'Bagerhat', 'Mongla'],
        ['Khulna', 'Bagerhat', 'Morrelganj'],
        ['Khulna', 'Bagerhat', 'Rampal'],
        ['Khulna', 'Bagerhat', 'Sarankhola'],
        ['Khulna', 'Chuadanga', 'Chuadanga Sadar'],
        ['Khulna', 'Chuadanga', 'Alamdanga'],
        ['Khulna', 'Chuadanga', 'Damurhuda'],
        ['Khulna', 'Chuadanga', 'Jibannagar'],
        ['Khulna', 'Jessore', 'Jessore Sadar'],
        ['Khulna', 'Jessore', 'Abhaynagar'],
        ['Khulna', 'Jessore', 'Bagherpara'],
        ['Khulna', 'Jessore', 'Chaugachha'],
        ['Khulna', 'Jessore', 'Jhikargachha'],
        ['Khulna', 'Jessore', 'Keshabpur'],
        ['Khulna', 'Jessore', 'Manirampur'],
        ['Khulna', 'Jessore', 'Sharsha'],
        ['Khulna', 'Jhenaidah', 'Jhenaidah Sadar'],
        ['Khulna', 'Jhenaidah', 'Maheshpur'],
        ['Khulna', 'Jhenaidah', 'Kaliganj'],
        ['Khulna', 'Jhenaidah', 'Kotchandpur'],
        ['Khulna', 'Jhenaidah', 'Shailkupa'],
        ['Khulna', 'Jhenaidah', 'Harinakunda'],
        ['Khulna', 'Khulna', 'Khulna Sadar'],
        ['Khulna', 'Khulna', 'Sonadanga'],
        ['Khulna', 'Khulna', 'Khalishpur'],
        ['Khulna', 'Khulna', 'Daulatpur'],
        ['Khulna', 'Khulna', 'Khan Jahan Ali'],
        ['Khulna', 'Khulna', 'Harintana'],
        ['Khulna', 'Khulna', 'Labanchora'],
        ['Khulna', 'Khulna', 'Digholia'],
        ['Khulna', 'Khulna', 'Phultala'],
        ['Khulna', 'Khulna', 'Rupsha'],
        ['Khulna', 'Khulna', 'Terokhada'],
        ['Khulna', 'Khulna', 'Batiaghata'],
        ['Khulna', 'Khulna', 'Dumuria'],
        ['Khulna', 'Kushtia', 'Kushtia Sadar'],
        ['Khulna', 'Kushtia', 'Kumarkhali'],
        ['Khulna', 'Kushtia', 'Khoksa'],
        ['Khulna', 'Kushtia', 'Mirpur'],
        ['Khulna', 'Kushtia', 'Daulatpur'],
        ['Khulna', 'Kushtia', 'Bheramara'],
        ['Khulna', 'Magura', 'Magura Sadar'],
        ['Khulna', 'Magura', 'Mohammadpur'],
        ['Khulna', 'Magura', 'Shalikha'],
        ['Khulna', 'Magura', 'Sreepur'],
        ['Khulna', 'Meherpur', 'Meherpur Sadar'],
        ['Khulna', 'Meherpur', 'Gangni'],
        ['Khulna', 'Meherpur', 'Mujibnagar'],
        ['Khulna', 'Narail', 'Narail Sadar'],
        ['Khulna', 'Narail', 'Lohagara'],
        ['Khulna', 'Narail', 'Kalia'],
        ['Khulna', 'Satkhira', 'Satkhira Sadar'],
        ['Khulna', 'Satkhira', 'Assasuni'],
        ['Khulna', 'Satkhira', 'Debhata'],
        ['Khulna', 'Satkhira', 'Tala'],
        ['Khulna', 'Satkhira', 'Kalaroa'],
        ['Khulna', 'Satkhira', 'Kaliganj'],
        ['Khulna', 'Satkhira', 'Shyamnagar'],
        
        // Mymensingh Division
        ['Mymensingh', 'Jamalpur', 'Jamalpur Sadar'],
        ['Mymensingh', 'Jamalpur', 'Melandaha'],
        ['Mymensingh', 'Jamalpur', 'Islampur'],
        ['Mymensingh', 'Jamalpur', 'Dewanganj'],
        ['Mymensingh', 'Jamalpur', 'Sarishabari'],
        ['Mymensingh', 'Jamalpur', 'Madarganj'],
        ['Mymensingh', 'Jamalpur', 'Bakshiganj'],
        ['Mymensingh', 'Mymensingh', 'Mymensingh Sadar'],
        ['Mymensingh', 'Mymensingh', 'Bhaluka'],
        ['Mymensingh', 'Mymensingh', 'Trishal'],
        ['Mymensingh', 'Mymensingh', 'Haluaghat'],
        ['Mymensingh', 'Mymensingh', 'Muktagachha'],
        ['Mymensingh', 'Mymensingh', 'Dhobaura'],
        ['Mymensingh', 'Mymensingh', 'Fulbaria'],
        ['Mymensingh', 'Mymensingh', 'Gaffargaon'],
        ['Mymensingh', 'Mymensingh', 'Gauripur'],
        ['Mymensingh', 'Mymensingh', 'Ishwarganj'],
        ['Mymensingh', 'Mymensingh', 'Nandail'],
        ['Mymensingh', 'Mymensingh', 'Phulpur'],
        ['Mymensingh', 'Netrokona', 'Netrokona Sadar'],
        ['Mymensingh', 'Netrokona', 'Barhatta'],
        ['Mymensingh', 'Netrokona', 'Durgapur'],
        ['Mymensingh', 'Netrokona', 'Khaliajuri'],
        ['Mymensingh', 'Netrokona', 'Kendua'],
        ['Mymensingh', 'Netrokona', 'Atpara'],
        ['Mymensingh', 'Netrokona', 'Madan'],
        ['Mymensingh', 'Netrokona', 'Mohanganj'],
        ['Mymensingh', 'Netrokona', 'Purbadhala'],
        ['Mymensingh', 'Sherpur', 'Sherpur Sadar'],
        ['Mymensingh', 'Sherpur', 'Jhenaigati'],
        ['Mymensingh', 'Sherpur', 'Nakla'],
        ['Mymensingh', 'Sherpur', 'Nalitabari'],
        ['Mymensingh', 'Sherpur', 'Sreebardi'],
        
        // Rajshahi Division
        ['Rajshahi', 'Bogra', 'Bogra Sadar'],
        ['Rajshahi', 'Bogra', 'Adamdighi'],
        ['Rajshahi', 'Bogra', 'Dhunat'],
        ['Rajshahi', 'Bogra', 'Dhupchanchia'],
        ['Rajshahi', 'Bogra', 'Gabtali'],
        ['Rajshahi', 'Bogra', 'Kahaloo'],
        ['Rajshahi', 'Bogra', 'Nandigram'],
        ['Rajshahi', 'Bogra', 'Sariakandi'],
        ['Rajshahi', 'Bogra', 'Shajahanpur'],
        ['Rajshahi', 'Bogra', 'Sherpur'],
        ['Rajshahi', 'Bogra', 'Shibganj'],
        ['Rajshahi', 'Bogra', 'Sonatala'],
        ['Rajshahi', 'Chapainawabganj', 'Chapainawabganj Sadar'],
        ['Rajshahi', 'Chapainawabganj', 'Gomastapur'],
        ['Rajshahi', 'Chapainawabganj', 'Bholahat'],
        ['Rajshahi', 'Chapainawabganj', 'Nachole'],
        ['Rajshahi', 'Chapainawabganj', 'Shibganj'],
        ['Rajshahi', 'Joypurhat', 'Joypurhat Sadar'],
        ['Rajshahi', 'Joypurhat', 'Akkelpur'],
        ['Rajshahi', 'Joypurhat', 'Kalai'],
        ['Rajshahi', 'Joypurhat', 'Khetlal'],
        ['Rajshahi', 'Joypurhat', 'Panchbibi'],
        ['Rajshahi', 'Naogaon', 'Naogaon Sadar'],
        ['Rajshahi', 'Naogaon', 'Atrai'],
        ['Rajshahi', 'Naogaon', 'Badalgachhi'],
        ['Rajshahi', 'Naogaon', 'Dhamoirhat'],
        ['Rajshahi', 'Naogaon', 'Manda'],
        ['Rajshahi', 'Naogaon', 'Mohadevpur'],
        ['Rajshahi', 'Naogaon', 'Niamatpur'],
        ['Rajshahi', 'Naogaon', 'Patnitala'],
        ['Rajshahi', 'Naogaon', 'Porsha'],
        ['Rajshahi', 'Naogaon', 'Raninagar'],
        ['Rajshahi', 'Naogaon', 'Sapahar'],
        ['Rajshahi', 'Natore', 'Natore Sadar'],
        ['Rajshahi', 'Natore', 'Baraigram'],
        ['Rajshahi', 'Natore', 'Bagatipara'],
        ['Rajshahi', 'Natore', 'Gurudaspur'],
        ['Rajshahi', 'Natore', 'Lalpur'],
        ['Rajshahi', 'Natore', 'Singra'],
        ['Rajshahi', 'Pabna', 'Pabna Sadar'],
        ['Rajshahi', 'Pabna', 'Atgharia'],
        ['Rajshahi', 'Pabna', 'Bera'],
        ['Rajshahi', 'Pabna', 'Bhangura'],
        ['Rajshahi', 'Pabna', 'Chatmohar'],
        ['Rajshahi', 'Pabna', 'Faridpur'],
        ['Rajshahi', 'Pabna', 'Ishwardi'],
        ['Rajshahi', 'Pabna', 'Santhia'],
        ['Rajshahi', 'Pabna', 'Sujanagar'],
        ['Rajshahi', 'Rajshahi', 'Rajshahi Metropoliton'],
        ['Rajshahi', 'Rajshahi', 'Bagha'],
        ['Rajshahi', 'Rajshahi', 'Bagmara'],
        ['Rajshahi', 'Rajshahi', 'Charghat'],
        ['Rajshahi', 'Rajshahi', 'Durgapur'],
        ['Rajshahi', 'Rajshahi', 'Godagari'],
        ['Rajshahi', 'Rajshahi', 'Mohanpur'],
        ['Rajshahi', 'Rajshahi', 'Paba'],
        ['Rajshahi', 'Rajshahi', 'Puthia'],
        ['Rajshahi', 'Rajshahi', 'Tanore'],
        ['Rajshahi', 'Sirajganj', 'Sirajganj Sadar'],
        ['Rajshahi', 'Sirajganj', 'Belkuchi'],
        ['Rajshahi', 'Sirajganj', 'Chauhali'],
        ['Rajshahi', 'Sirajganj', 'Kamarkhanda'],
        ['Rajshahi', 'Sirajganj', 'Kazipur'],
        ['Rajshahi', 'Sirajganj', 'Raiganj'],
        ['Rajshahi', 'Sirajganj', 'Shahjadpur'],
        ['Rajshahi', 'Sirajganj', 'Tarash'],
        ['Rajshahi', 'Sirajganj', 'Ullahpara'],
        
        // Rangpur Division
        ['Rangpur', 'Dinajpur', 'Dinajpur Sadar'],
        ['Rangpur', 'Dinajpur', 'Birampur'],
        ['Rangpur', 'Dinajpur', 'Birganj'],
        ['Rangpur', 'Dinajpur', 'Biral'],
        ['Rangpur', 'Dinajpur', 'Bochaganj'],
        ['Rangpur', 'Dinajpur', 'Chirirbandar'],
        ['Rangpur', 'Dinajpur', 'Phulbari'],
        ['Rangpur', 'Dinajpur', 'Ghoraghat'],
        ['Rangpur', 'Dinajpur', 'Hakimpur'],
        ['Rangpur', 'Dinajpur', 'Kaharole'],
        ['Rangpur', 'Dinajpur', 'Khansama'],
        ['Rangpur', 'Dinajpur', 'Nawabganj'],
        ['Rangpur', 'Dinajpur', 'Parbatipur'],
        ['Rangpur', 'Gaibandha', 'Gaibandha Sadar'],
        ['Rangpur', 'Gaibandha', 'Fulchhari'],
        ['Rangpur', 'Gaibandha', 'Gobindaganj'],
        ['Rangpur', 'Gaibandha', 'Palashbari'],
        ['Rangpur', 'Gaibandha', 'Sadullapur'],
        ['Rangpur', 'Gaibandha', 'Saghata'],
        ['Rangpur', 'Gaibandha', 'Sundarganj'],
        ['Rangpur', 'Kurigram', 'Kurigram Sadar'],
        ['Rangpur', 'Kurigram', 'Bhurungamari'],
        ['Rangpur', 'Kurigram', 'Char Rajibpur'],
        ['Rangpur', 'Kurigram', 'Chilmari'],
        ['Rangpur', 'Kurigram', 'Phulbari'],
        ['Rangpur', 'Kurigram', 'Nageshwari'],
        ['Rangpur', 'Kurigram', 'Rajarhat'],
        ['Rangpur', 'Kurigram', 'Raomari'],
        ['Rangpur', 'Kurigram', 'Ulipur'],
        ['Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar'],
        ['Rangpur', 'Lalmonirhat', 'Aditmari'],
        ['Rangpur', 'Lalmonirhat', 'Kaliganj'],
        ['Rangpur', 'Lalmonirhat', 'Hatibandha'],
        ['Rangpur', 'Lalmonirhat', 'Patgram'],
        ['Rangpur', 'Nilphamari', 'Nilphamari Sadar'],
        ['Rangpur', 'Nilphamari', 'Dimla'],
        ['Rangpur', 'Nilphamari', 'Domar'],
        ['Rangpur', 'Nilphamari', 'Jaldhaka'],
        ['Rangpur', 'Nilphamari', 'Kishoreganj'],
        ['Rangpur', 'Nilphamari', 'Saidpur'],
        ['Rangpur', 'Panchagarh', 'Panchagarh Sadar'],
        ['Rangpur', 'Panchagarh', 'Atwari'],
        ['Rangpur', 'Panchagarh', 'Boda'],
        ['Rangpur', 'Panchagarh', 'Debiganj'],
        ['Rangpur', 'Panchagarh', 'Tetulia'],
        ['Rangpur', 'Rangpur', 'Rangpur Sadar'],
        ['Rangpur', 'Rangpur', 'Badarganj'],
        ['Rangpur', 'Rangpur', 'Gangachara'],
        ['Rangpur', 'Rangpur', 'Kaunia'],
        ['Rangpur', 'Rangpur', 'Mithapukur'],
        ['Rangpur', 'Rangpur', 'Pirganj'],
        ['Rangpur', 'Rangpur', 'Pirgachha'],
        ['Rangpur', 'Rangpur', 'Taraganj'],
        ['Rangpur', 'Thakurgaon', 'Thakurgaon Sadar'],
        ['Rangpur', 'Thakurgaon', 'Baliadangi'],
        ['Rangpur', 'Thakurgaon', 'Haripur'],
        ['Rangpur', 'Thakurgaon', 'Pirganj'],
        ['Rangpur', 'Thakurgaon', 'Ranisankail'],
        
        // Sylhet Division
        ['Sylhet', 'Habiganj', 'Habiganj Sadar'],
        ['Sylhet', 'Habiganj', 'Ajmiriganj'],
        ['Sylhet', 'Habiganj', 'Baniachang'],
        ['Sylhet', 'Habiganj', 'Bahubal'],
        ['Sylhet', 'Habiganj', 'Chunarughat'],
        ['Sylhet', 'Habiganj', 'Lakhai'],
        ['Sylhet', 'Habiganj', 'Madhabpur'],
        ['Sylhet', 'Habiganj', 'Nabiganj'],
        ['Sylhet', 'Moulvibazar', 'Moulvibazar Sadar'],
        ['Sylhet', 'Moulvibazar', 'Barlekha'],
        ['Sylhet', 'Moulvibazar', 'Juri'],
        ['Sylhet', 'Moulvibazar', 'Kamalganj'],
        ['Sylhet', 'Moulvibazar', 'Kulaura'],
        ['Sylhet', 'Moulvibazar', 'Rajnagar'],
        ['Sylhet', 'Moulvibazar', 'Sreemangal'],
        ['Sylhet', 'Sunamganj', 'Sunamganj Sadar'],
        ['Sylhet', 'Sunamganj', 'Bishwamvarpur'],
        ['Sylhet', 'Sunamganj', 'Chhatak'],
        ['Sylhet', 'Sunamganj', 'Derai'],
        ['Sylhet', 'Sunamganj', 'Dharampasha'],
        ['Sylhet', 'Sunamganj', 'Dowarabazar'],
        ['Sylhet', 'Sunamganj', 'Jagannathpur'],
        ['Sylhet', 'Sunamganj', 'Jamalganj'],
        ['Sylhet', 'Sunamganj', 'Sullah'],
        ['Sylhet', 'Sunamganj', 'Tahirpur'],
        ['Sylhet', 'Sylhet', 'Sylhet Metropoliton'],
        ['Sylhet', 'Sylhet', 'Beanibazar'],
        ['Sylhet', 'Sylhet', 'Bishwanath'],
        ['Sylhet', 'Sylhet', 'Companiganj'],
        ['Sylhet', 'Sylhet', 'Fenchuganj'],
        ['Sylhet', 'Sylhet', 'Golapganj'],
        ['Sylhet', 'Sylhet', 'Gowainghat'],
        ['Sylhet', 'Sylhet', 'Jaintiapur'],
        ['Sylhet', 'Sylhet', 'Kanaighat'],
        ['Sylhet', 'Sylhet', 'Zakiganj'],
        ['Sylhet', 'Sylhet', 'Balaganj']
    ];
    
    // Prepare and execute insert statement
    $stmt = $conn->prepare("INSERT INTO thanas_master (division, district, thana_name) VALUES (?, ?, ?)");
    if (!$stmt) die("Error preparing thana insert: " . $conn->error);
    
    foreach ($thana_data as $thana) {
        $stmt->bind_param("sss", $thana[0], $thana[1], $thana[2]);
        if (!$stmt->execute()) die("Error inserting thana: " . $stmt->error);
    }
    $stmt->close();
}



